default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/horta/sanitize-pyproject-version
    rev: v0.0.4
    hooks:
      - id: check-version-equality
